function arr=FileFrame(fileinfo,frame)

%arr=FileFrame(fileinfo,frame)
%
%FileFrame.m is a front end which unifies the commands necessary to read
%frames from common file formats. Memory limitations make it advisable to 
%read individual frames, rather than the entire movie at once, when 
%possible. 
%
%INCLUDE:   SpeFrame.m
%           SifFrame.m
%           CineFrame.m
%           ReadRoot.m
%
%INPUTS:    FILEINFO:   A structure containing pertinent information about
%                       the file, generated by FileDetails.m
%           FRAME:      The index of the frame to be read.
%
%OUTPUTS:   ARR:     A matrix representation of the relevant frame.
%
%Copyright Stephen Anthony 10/2009 U. Illinois Urbana-Champaign
%Last modified by Stephen Anthony on 10/03/2009

%Call the appropriate function dependent upon file type, by comparing the
%file extension in a non-case sensitive fashion
if strcmpi(fileinfo.format,'.sif')
    %Andor Technology MultiChannel File Format
    arr=SifFrame(fileinfo,frame);
elseif strcmpi(fileinfo.format,'.spe')
    %SPE File format (WinSpec)
    arr=SpeFrame(fileinfo,frame);
elseif strcmpi(fileinfo.format,'.cine')
    %CINE Vision Research File Format
    arr=CineFrame(fileinfo,frame);
elseif strcmpi(fileinfo.format,'.root')
    arr=ReadRoot(fileinfo,frame,'frames');
end