function row=SifRow(fileinfo,rownum)

%row=SifRow(fileinfo,framenum,rownum)
%
%While typically, frame by frame operation is more desireable, sometimes it
%is necessary to know the value of a pixel at all times. Generally, memory
%limitations prohibit reading in all values of all pixels. As a compromise,
%instead of operating upon all pixels at all times, we operate upon a row
%of pixels at all times. 
%
%INCLUDE:   
%
%INPUTS:    FILEINFO:   A structure containing pertinent information about
%                       the file, generated by FileDetails.m
%           FRAMENUM:   The index of the frame to be read.
%           ROWNUM:     The y coordinate in the array of the desired row.
%
%
%OUTPUTS:   ROW:     An array, for which each row gives the value of the
%                       selected row at the corresponding frame number
%
%Copyright Stephen Anthony 07/2007 U. Illinois Urbana-Champaign
%Last modified by Stephen Anthony on 06/22/2009

%Open up the desired file.
fid=fopen(fileinfo.location,'r'); 

%Calculate the offset for this pixel
rowoff=(fileinfo.dimX*(rownum-1))*4;

row=zeros(fileinfo.Nframes,fileinfo.dimX);

for ii = 1:fileinfo.Nframes
    newpos=fileinfo.datastart+fileinfo.dimX*fileinfo.dimY*(ii-1)*4+rowoff;
    %Adjust the position to the desired positions
    fseek(fid,newpos,-1);
    %Read in the pixel
    row(ii,:)=fread(fid,fileinfo.dimX,'float32=>float32');
end
%Close the file
fclose(fid);


   